export const JobDataScientist = [
  {
    title: 'Data Scientist',
    type: 'Full Time',
    company: 'SCB',
    companyLogo: '/images/company/scb.svg',
    salary: '25,000 - 35,000',
    location: 'Bangkok',
  },
  {
    title: 'Data Scientist',
    type: 'Full Time',
    company: 'TMB',
    companyLogo: '/images/company/tmb.svg',
    salary: '45,000 - 60,000',
    location: 'Bangkok',
  },
  {
    title: 'Data Scientist',
    type: 'Full Time',
    company: 'Mitr-phol',
    companyLogo: '/images/company/mitr-phol.svg',
    salary: '35,000 - 80,000',
    location: 'Bangkok',
  },
  {
    title: 'Data Scientist',
    type: 'Full Time',
    company: 'PTT',
    companyLogo: '/images/company/ptt.svg',
    salary: '30,000 - 50,000',
    location: 'Bangkok',
  },
  {
    title: 'IT - Data Scientist',
    type: 'Full Time',
    company: 'Krungsri',
    companyLogo: '/images/company/krungsri.svg',
    salary: '30,000 - 40,000',
    location: 'Nontaburi',
  },
  {
    title: 'Data Scientist',
    type: 'Full Time',
    company: 'SET',
    companyLogo: '/images/company/set.svg',
    salary: '25,000 - 40,000',
    location: 'Rayong',
  },
]
