export const JobData = [
  {
    title: 'Data Analyst',
    type: 'Full Time',
    company: 'AIS',
    companyLogo: '/images/company/ais.svg',
    salary: '25,000 - 35,000',
    location: 'Bangkok',
  },
  {
    title: 'Data Analyst',
    type: 'Full Time',
    company: 'SET',
    companyLogo: '/images/company/set.svg',
    salary: '30,000 - 45,000',
    location: 'Rayong',
  },
  {
    title: 'Data Analyst',
    type: 'Full Time',
    company: 'PTT',
    companyLogo: '/images/company/ptt.svg',
    salary: '40,000 - 50,000',
    location: 'Bangkok',
  },
  {
    title: 'Data Analyst',
    type: 'Full Time',
    company: 'Krungsri',
    companyLogo: '/images/company/krungsri.svg',
    salary: '30,000 - 45,000',
    location: 'Nontaburi',
  },
  {
    title: 'Data Analyst',
    type: 'Full Time',
    company: 'Mitr-phol',
    companyLogo: '/images/company/mitr-phol.svg',
    salary: '35,000 - 40,000',
    location: 'Bangkok',
  },
  {
    title: 'Data Analyst',
    type: 'Full Time',
    company: 'TMB',
    companyLogo: '/images/company/tmb.svg',
    salary: '45,000 - 50,000',
    location: 'Bangkok',
  },
]
